// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuBvLloO4oPjccDl0QsVC6zgJ7nCEQxFw',
    appId: '1:652813651851:web:f5cb53e1a7e13cb813e98e',
    messagingSenderId: '652813651851',
    projectId: 'prime-team-230618',
    authDomain: 'prime-team-230618.firebaseapp.com',
    storageBucket: 'prime-team-230618.appspot.com',
    measurementId: 'G-EQ2X92GBHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz-tWSgNNFHnkJLIHF6glBqOhD55xdCDs',
    appId: '1:652813651851:android:9a4a377efad4e77013e98e',
    messagingSenderId: '652813651851',
    projectId: 'prime-team-230618',
    storageBucket: 'prime-team-230618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClAFdkCYKlMNKbEKY86k2LmG_9C_I6GAo',
    appId: '1:652813651851:ios:5162ed80bd04737913e98e',
    messagingSenderId: '652813651851',
    projectId: 'prime-team-230618',
    storageBucket: 'prime-team-230618.appspot.com',
    androidClientId: '652813651851-uhi742onvbffp3lqsmu3sfkqmlu6bff3.apps.googleusercontent.com',
    iosClientId: '652813651851-4pqd1lih8oc63abup7spt4fj3gptj8hq.apps.googleusercontent.com',
    iosBundleId: 'com.idea.portal',
  );
}
